module.exports = {
  cuisines: [
    { label: 'Select Cuisines', value: '0' },
    { label: 'African', value: 'African' },
    { label: 'American', value: 'American' },
    { label: 'Argentinian', value: 'Argentinian' },
    { label: 'Asian', value: 'Asian' },
    { label: 'Asian Fusion', value: 'Asian Fusion' },
    { label: 'British', value: 'British' },
    { label: 'Caribbean', value: 'Caribbean' },
    { label: 'Chinese', value: 'Chinese' },
    { label: 'Ethiopian', value: 'Ethiopian' },
    { label: 'European', value: 'European' },
    { label: 'French', value: 'French' },
    { label: 'Greek', value: 'Greek' },
    { label: 'Indian', value: 'Indian' },
    { label: 'International', value: 'International' },
    { label: 'Italian', value: 'Italian' },
    { label: 'Jamaican', value: 'Jamaican' },
    { label: 'Japanese', value: 'Japanese' },
    { label: 'Korean', value: 'Korean' },
    { label: 'Lebanese', value: 'Lebanese' },
    { label: 'Nigerian', value: 'Nigerian' },
    { label: 'Malaysian', value: 'Malaysian' },
    { label: 'Mediterranean', value: 'Mediterranean' },
    { label: 'Mexican', value: 'Mexican' },
    { label: 'Middle Eastern', value: 'Middle Eastern' },
    { label: 'Pan Asian', value: 'Pan Asian' },
    { label: 'Portugese', value: 'Portugese' },
    { label: 'Sichuan', value: 'Sichuan' },
    { label: 'South American', value: 'South American' },
    { label: 'Spanish', value: 'Spanish' },
    { label: 'Tiwanese', value: 'Tiwanese' },
    { label: 'Thai', value: 'Thai' },
    { label: 'Turkish', value: 'Turkish' },
    { label: 'Vietnamese', value: 'Vietnamese' },
    { label: 'Western', value: 'Western' },
    { label: 'Others', value: 'Others' }
  ],
  deliveryareas: [
    { label: 'Select Delivery Areas', value: '0' },
    { label: 'Ikota-Graceland estate', value: 'Ikota-Graceland estate' },
    { label: 'Iju-Fagba', value: 'Iju-Fagba' },
    { label: 'Egbeda', value: 'Egbeda' },
    { label: 'Mile 2', value: 'Mile 2' },
    { label: 'Bariga', value: 'Bariga' },
    { label: 'Ajuwon-Lambe', value: 'Ajuwon-Lambe' },
    { label: 'Costain-Ijora Olopa', value: 'Costain-Ijora Olopa' },
    { label: 'Shangotedo', value: 'Shangotedo' },
    { label: 'Abule Egba', value: 'Abule Egba' },
    { label: 'Ikota-Thomas estate', value: 'Ikota-Thomas estate' },
    { label: 'Shangisha', value: 'Shangisha' },
    { label: 'Ikota-Badore', value: 'Ikota-Badore' },
    { label: 'Amuwo Odofin', value: 'Amuwo Odofin' },
    { label: 'Magodo Phase 1', value: 'Magodo Phase 1' },
    { label: 'Yaba', value: 'Yaba' },
    { label: 'Lekki - Chevron', value: 'Lekki - Chevron' },
    { label: 'Ikoyi', value: 'Ikoyi' },
    { label: 'Festac', value: 'Festac' },
    { label: 'Ikeja Opebi', value: 'Ikeja Opebi' },
    { label: 'Ikeja Maryland', value: 'Ikeja Maryland' },
    { label: 'Ikeja GRA', value: 'Ikeja GRA' },
    { label: 'Ikeja-Adeniyi Jones', value: 'Ikeja-Adeniyi Jones' },
    { label: 'Ikeja Oba Akran', value: 'Ikeja Oba Akran' },
    { label: 'Anthony village', value: 'Anthony village' },
    { label: 'Satelite town', value: 'Satelite town' },
    { label: 'Ipaja', value: 'Ipaja' },
    { label: 'Mushin', value: 'Mushin' },
    { label: 'Alagbado', value: 'Alagbado' },
    { label: 'Akoka', value: 'Akoka' },
    { label: 'Apapa', value: 'Apapa' },
    { label: 'Sabo', value: 'Sabo' },
    { label: 'Ifako-Ijaiye', value: 'Ifako-Ijaiye' },
    { label: 'Ojodu berger', value: 'Ojodu berger' },
    { label: 'Igando', value: 'Igando' },
    { label: 'Ikota-Crown Estate', value: 'Ikota-Crown Estate' },
    { label: 'Iyana Ipaja', value: 'Iyana Ipaja' },
    { label: 'Ikotun', value: 'Ikotun' },
    { label: 'Ojuelegba', value: 'Ojuelegba' },
    {
      label: 'Surelere - National Stadium',
      value: 'Surelere - National Stadium'
    },
    { label: 'Jibowu-Fadeyi', value: 'Jibowu-Fadeyi' },
    { label: 'Surulere, Aguda', value: 'Surulere, Aguda' },
    { label: 'Ogudu', value: 'Ogudu' },
    { label: 'Lagos Island', value: 'Lagos Island' },
    { label: 'Lekki Phase 2', value: 'Lekki Phase 2' },
    { label: 'Ikeja Allen', value: 'Ikeja Allen' },
    { label: 'Ikota', value: 'Ikota' },
    { label: 'Mende', value: 'Mende' },
    { label: 'Jumia - Ikeja', value: 'Jumia - Ikeja' },
    { label: 'Lekki Phase 1', value: 'Lekki Phase 1' },
    { label: 'Ikoyi - Bourdillon', value: 'Ikoyi - Bourdillon' },
    { label: 'VGC', value: 'VGC' },
    { label: 'Dopemu', value: 'Dopemu' },
    { label: 'Ejigbo', value: 'Ejigbo' },
    { label: 'Ojota', value: 'Ojota' },
    { label: 'Agbado Railway', value: 'Agbado Railway' },
    { label: 'Gowon Estate', value: 'Gowon Estate' },
    { label: 'Ikota-Igbo Efun', value: 'Ikota-Igbo Efun' },
    { label: 'Local Airport Road', value: 'Local Airport Road' },
    { label: 'Okokomaiko', value: 'Okokomaiko' },
    { label: 'Unilag', value: 'Unilag' },
    { label: 'Ebute-Metta', value: 'Ebute-Metta' },
    { label: 'Surulere - Bode Thomas', value: 'Surulere - Bode Thomas' },
    { label: 'Gbagada', value: 'Gbagada' },
    { label: 'Surulere', value: 'Surulere' },
    { label: 'Jumia', value: 'Jumia' },
    { label: 'Ikoyi Dolphin Estate', value: 'Ikoyi Dolphin Estate' },
    { label: 'Lekki - Jakande', value: 'Lekki - Jakande' },
    { label: 'Ikoyi - Awolowo', value: 'Ikoyi - Awolowo' },
    { label: 'Marina', value: 'Marina' },
    { label: 'Obalende', value: 'Obalende' },
    { label: 'Ikeja Alausa', value: 'Ikeja Alausa' },
    { label: 'Ilupeju', value: 'Ilupeju' },
    { label: 'Epe', value: 'Epe' },
    { label: 'Okota', value: 'Okota' },
    { label: 'Egbeda Akowonjo', value: 'Egbeda Akowonjo' },
    { label: 'Local Airport', value: 'Local Airport' },
    { label: 'Ajah', value: 'Ajah' },
    { label: 'E-center Food court', value: 'E-center Food court' },
    {
      label: 'Ikota-Abraham Adesanya Estate',
      value: 'Ikota-Abraham Adesanya Estate'
    },
    { label: 'Oshodi', value: 'Oshodi' },
    { label: 'Iyana Iba - Lasu', value: 'Iyana Iba - Lasu' },
    { label: 'Ogba', value: 'Ogba' },
    { label: 'PWC Guest Area', value: 'PWC Guest Area' },
    { label: 'Ketu', value: 'Ketu' },
    { label: 'Akute-Ajuwon', value: 'Akute-Ajuwon' },
    { label: 'Ikorodu', value: 'Ikorodu' },
    { label: 'Idimu', value: 'Idimu' },
    { label: 'Ibeju Lekki', value: 'Ibeju Lekki' },
    { label: 'Somolu', value: 'Somolu' },
    { label: 'Ikota Shopping Complex', value: 'Ikota Shopping Complex' },
    { label: 'Magodo Phase II', value: 'Magodo Phase II' },
    { label: 'Victoria Island', value: 'Victoria Island' },
    { label: 'Banana Island', value: 'Banana Island' },
    { label: 'Chisco', value: 'Chisco' },
    {
      label: 'Lekki - 4th & 5th Roundabout',
      value: 'Lekki - 4th & 5th Roundabout'
    },
    {
      label: 'Ikeja Mobolaji Bank Anthony',
      value: 'Ikeja Mobolaji Bank Anthony'
    },
    { label: 'Ikeja- Awolowo road', value: 'Ikeja- Awolowo road' },
    { label: 'Anthony', value: 'Anthony' }
  ],
  categories: [
    'African',
    'Alcoholic Drinks',
    'American',
    'Asian',
    'Bakery and Confectionery',
    'Bar and Lounge',
    'Beverages',
    'Breakfast',
    'Burger',
    'Cafe & Coffee',
    'European',
    'Fast Food',
    'Fit Fam',
    'Home Made Food',
    'Traditional Cuisine',
    'International',
    'Pizza',
    'Seafood',
    'Vegetarian'
  ]
};
